"""empty message

Revision ID: 01f2ef00182c
Revises: de83228473e4
Create Date: 2022-12-31 15:05:37.503202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01f2ef00182c'
down_revision = 'de83228473e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('current_photos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('counter', sa.Integer(), nullable=True))
        batch_op.drop_column('current_photo_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('current_photos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_photo_id', sa.INTEGER(), nullable=True))
        batch_op.drop_column('counter')

    # ### end Alembic commands ###
