"""empty message

Revision ID: 196c87e2b0f4
Revises: 498a8b705cc8
Create Date: 2022-12-25 18:35:07.827355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '196c87e2b0f4'
down_revision = '498a8b705cc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('register_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('register_codes')
    # ### end Alembic commands ###
