"""empty message

Revision ID: 19a330d19d68
Revises: 01f2ef00182c
Create Date: 2023-01-05 18:45:34.448548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19a330d19d68'
down_revision = '01f2ef00182c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('current_photos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_date', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('current_photos', schema=None) as batch_op:
        batch_op.drop_column('current_date')

    # ### end Alembic commands ###
