"""empty message

Revision ID: 3af5c6a1076d
Revises: 196c87e2b0f4
Create Date: 2022-12-25 18:37:38.716175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3af5c6a1076d'
down_revision = '196c87e2b0f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('register_codes', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=8),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('register_codes', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.String(length=8),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)

    # ### end Alembic commands ###
