"""empty message

Revision ID: 3b16cc4bf37d
Revises: 243dcbdac999
Create Date: 2022-12-31 14:23:45.922252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b16cc4bf37d'
down_revision = '243dcbdac999'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_counters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_photo_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('current_photo', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('current_message', sa.String(length=256), nullable=True))
        batch_op.drop_column('counter')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_counters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('counter', sa.INTEGER(), nullable=True))
        batch_op.drop_column('current_message')
        batch_op.drop_column('current_photo')
        batch_op.drop_column('current_photo_id')

    # ### end Alembic commands ###
