"""empty message

Revision ID: 498a8b705cc8
Revises: 92cd9b2379df
Create Date: 2022-12-21 20:17:14.908245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '498a8b705cc8'
down_revision = '92cd9b2379df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photos_and_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo_name', sa.String(length=128), nullable=True),
    sa.Column('message', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('messages')
    op.drop_table('photos')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('photo_name', sa.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('message', sa.VARCHAR(length=256), nullable=True),
    sa.Column('photo_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('photo_id')
    )
    op.drop_table('photos_and_messages')
    # ### end Alembic commands ###
