"""empty message

Revision ID: 92cd9b2379df
Revises: 0d4edb1f319b
Create Date: 2022-12-21 18:28:11.828944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92cd9b2379df'
down_revision = '0d4edb1f319b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo_name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=256), nullable=True),
    sa.Column('photo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('photo_id')
    )
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('is_private')
        batch_op.drop_column('intro')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('intro', sa.VARCHAR(length=256), nullable=True))
        batch_op.add_column(sa.Column('is_private', sa.BOOLEAN(), nullable=True))

    op.drop_table('messages')
    op.drop_table('photos')
    # ### end Alembic commands ###
